### ISSUE TITLE
Make calendar period to get configurable & enable multiple sensors

### ISSUE THREAD

**Issue by gijbelsy** [PTST/O365Calendar-HomeAssistant#17]
Since I've got the component working and all is looking  good, I would like to do some feature requests:

- Component only looks 24Hrs ahead, possibility to change this in the configuration.yaml
Maybe do something with start/end date/time?

- Possibility to create multiple sensors, each for a (shared) calendar

**Comment by PTST** [comment]
That is certainly possible. I have put it on the to-do list

**Comment by PTST** [comment]
### Notes to self for implementing this

The following changes will as a minimum be needed to enable multiple sensors

- Setting the name of the sensor in the configuration.yaml. 
- Setting the name of the calendar to use and if not set use default calendar as now.

Regarding making the period configurable, this should be as easy as just changing the code from getting todays events to getting the next x hours events and then making the number of hours configurable via the configuration.yaml with a default value of 24. 

It might also be nice to give the option of setting a number of hours back in time to include. I can see a couple of potential automation use cases using earlier events.

**Comment by gijbelsy** [comment]
Is a datetime from and datetime to parameter more convenient ?
Say if I want to make a wake-me-up event, then I want to look only if there is an event in the morning, the next day...

**Comment by PTST** [comment]
Then you would have to change your configuration.yaml every day with a new date wouldn't you?

There is actually already a service you can call at *office365calendar.get_calendar_events* here you can specify at start and end datetime, this creates a new sensor with the events for this period.

You can also specify the calendar name in this service call and you should be able to access shared calendars this way. But that part is completely untested on my end for now

**Comment by gijbelsy** [comment]
True.

I'll test the service call, see what this does.
Before this custom component I used Google Calendar, as embedded in HA.
For each calendar I had an entity defined.

**Comment by PTST** [comment]
Hello i have added these features in the latest version https://github.com/PTST/O365Calendar-HomeAssistant/releases/tag/v1.1
