### ISSUE TITLE
Home assistant is not installing needed dependencies

### ISSUE THREAD

**Issue by cerebrate** [PTST/O365Calendar-HomeAssistant#18]
I'm having the same problem as #4 . After installing from HACS, I get a config validating notification when trying to restart HA, and the following in the logs:

```
2020-01-11 12:36:51 ERROR (MainThread) [homeassistant.components.hassio] Platform error sensor.office365calendar - No module named 'O365'
```

(Running hass.io in Docker.)

**Comment by PTST** [comment]
Hello

Can you please provide me with the following

* your home assistant version

Older versions of home assistant did have an issue where you had to do the following;
1. Install the component.
2. Restart home assistant.
3. Then add the sensor to your configuration.yaml
4. Restart home assistant again. 

Now rebooting twice should not be needed in version post 0.100 but it's worth giving it a shot

**Comment by cerebrate** [comment]
Sure. I'm on 0.103.6.

Looks like the double-reboot requirement is back, though.

**Comment by PTST** [comment]
Did the second reboot fix the issue for you?

**Comment by cerebrate** [comment]
It did, yes.

**Comment by PTST** [comment]
Great! I will make a note of this in the Readme for now and close this issue. I can se on the home assistant forums that the developers seems aware of this issue so I'll wait and see what the next releases will bring.
