### ISSUE TITLE
Issues with this long awaited integration (Redirect uri is not valid)

### ISSUE THREAD

**Issue by plexat** [PTST/O365Calendar-HomeAssistant#19]
Hi Patrick,
my issue as mentioned in the community:
I installed according the instructions. I get the request to verify (capture_1)
When I click I get to fill out my username and then I get an error (cap_2)
See setting in Azure. (cap_3 and cap_4)

Also attached my log file.

I really would like this to work so any help is appreciated!
Thank you.
Eric

![Capture_1](https://user-images.githubusercontent.com/48410668/72218694-1da7c480-353e-11ea-8991-a119dcef37ed.JPG)
![Capture_2](https://user-images.githubusercontent.com/48410668/72218714-52b41700-353e-11ea-92ba-86ec63f37cba.JPG)
![Capture_3](https://user-images.githubusercontent.com/48410668/72218702-226c7880-353e-11ea-8ad2-7e8a3f01facc.JPG)
![Capture_4](https://user-images.githubusercontent.com/48410668/72218704-24363c00-353e-11ea-9a44-f701dd35ec2a.JPG)
[home-assistant.log](https://github.com/PTST/O365Calendar-HomeAssistant/files/4050634/home-assistant.log)

**Comment by PTST** [comment]
can you please right click on the "Link O365 account" and provide me with that?

Is your home assistant instance available outside of your local network? The redirect url you have provided is a local ip and i do not know if this will work. But in any case it seems that you are missing the hom eassistant port in your redirect URI, if you have not changed it, then is should probably be 
```
http://192.168.154.178:8123/api/o365
```
Note the :8123 in the new url

**Comment by PTST** [comment]
Hello

I have just pushed V1.1 https://github.com/PTST/O365Calendar-HomeAssistant/releases/tag/v1.1

In this i have enabled an alternative auth flow that you can try https://github.com/PTST/O365Calendar-HomeAssistant/#alt-auth-flow

**Comment by chansearrington** [comment]
I think I'm having this same problem when trying to use Nabu Casa remote to do this.

The redirect URL works, but the application isn't routing to the correct URL.

Going to https://[unid].ui.nabu.casa/api/o365 results in a webpage that says, "Success! This window can be closed"

But! :-)

When I right click on the url from the notification I can see that it's trying to use my local ip address. (see below)

Might be cool to allow the URL to be configured by the user OR automatically pull the Nabu Casa URL from HA (not sure if you can do this. 

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=1f911a16-68b2-44dd-9a1e-cdcb91e21c34&redirect_uri=http%3A%2F%2F192.168.1.42%3A8123%2Fapi%2Fo365&scope=offline_access+User.Read+Calendars.Read+Calendars.Read.Shared&state=3ygbsInfLtmopGRnj7OVb8jXeyRPq0&access_type=offline

**Comment by PTST** [comment]
Chanse I could kiss you right now :kissing:

I would never have thought that this was the issue but of course

This I because you need to set your base url in you configuration.yaml

https://www.home-assistant.io/integrations/http/#base_url

Without that set home assistant just assumes that it is being accessed through the local ip

**Comment by PTST** [comment]
@plexat i assume that your install is working as well, if not please just reopen this issue

**Comment by plexat** [comment]
Hi Patrick,

Not yet solved for me but I am afraid it is because of access from outside my local network.

I first manage that and then see if the issue still exists.

Thanks for your patience and help so far.

 

Sincerely,
Eric

**Comment by PTST** [comment]
The alternative authentication method should work without external access

**Comment by chansearrington** [comment]
Worked for me.

**Comment by plexat** [comment]
Hello Patrick,

I was abroad for a few days so my apologies not responding.

The step to alter the url on Azure with the port number is done.

The next step, kissing Chanse, is not clear to me. 😊

                Chanse I could kiss you right now 😗

I would never have thought that this was the issue but of course

This I because you need to set your base url in you configuration.yaml

https://www.home-assistant.io/integrations/http/#base_url

 

What should I add and where?

I am very new to HA so it might be a stupid question but please be patient with me.

 

Hope to hear form you because I saw it worked for Chanse!

 

Sincerely,

Eric

**Comment by plexat** [comment]
Hi Patrick,
I could authorize but still got a message false in the entity box.
![Capture](https://user-images.githubusercontent.com/48410668/72752813-76710000-3bc3-11ea-8a38-ec8b71b19c64.PNG)

**Comment by PTST** [comment]
The sensor state is always just True/False, that just indicates whether you have an active event in you calendar right now.

You need to look at the sensor attributes to actually get the event info.
