### ISSUE TITLE
create calendar object

### ISSUE THREAD

**Issue by fierland** [PTST/O365Calendar-HomeAssistant#29]
**Describe the solution you'd like**
Is it possible to also create a Calendar object

**Comment by PTST** [comment]
Do you want to be able to create an entire new calendar from home assistant?

I'm struggling to see the use case for this?

**Comment by crazyfx1** [comment]
I think @fierland means that the component should provide a calendar entity in home-assistant instead of the sensor entity. Just like the Google Calender or Caldav component do.

**Comment by PTST** [comment]
#34
