### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by gijbelsy** [PTST/O365Calendar-HomeAssistant#4]
The compiler is missing the dependencies as stated in the manifest.json.
Where can I find these / install them?
(Running on HASS.IO)

**Comment by PTST** [comment]
All dependencies are available on pypi. And Hass should therefore download and install them automatically. 

Are you installing this component via HACS or manually your self? 

What kind of error are you getting?

**Comment by gijbelsy** [comment]
The error I'm getting is that de required dependencies are not found on the system.
Note that I'm using Hass.IO in a virtual enviorment, instead HomeAssistant. So automatic installation of dependencies isn't carried out (I think).
Even when I copy O365 and BeautifulSoup4 to the dep folder of HA, it gives me the same 'dependencies missing' error.

**Comment by PTST** [comment]
I am running Hass.io via docker myself, which should be roughly the same as running it in a virtual machine

Are you installing this component via HACS or manually by putting it inside custom_components? 

Can you please provide the full logs from home assistant?

**Comment by gijbelsy** [comment]
I just tested it again, and for some reason the dependencies started working. Maybe I've made a typo somewhere ?

**Comment by PTST** [comment]
In any case iøm glad you got i working 😄
