### ISSUE TITLE
Help with sending emails via the notify.o365_email service

### ISSUE THREAD

**Issue by Je-sse** [PTST/O365Calendar-HomeAssistant#99]
I installed this Office 365 integration into my Home Assistant installation and the calendar shows all my appointments now, that's great!
I want to try to use my Office 365 account for sending some emails, but I don't manage to get it work. I tried to test this functionality with the Developer Tools first by call the notify.o365_email service, but the only error message I get is:
Failed to call service notify/o365_email. expected a dictionary for dictionary value @ data['data']

The documentation shows that only the "message" key is required (if not configured it should use the configured account's email address to send to). But no matter what I try, nothing works:

`message: test`

`message: "test"`

```
message: test
title: test
target: email@provider.com
```

I think I'm doing something wrong, but I cannot find out what it is. Can someone tell me what I'm missing?

**Comment by Competizione** [comment]
Hi Je-sse, i had succsess with:

message: test
title: test
data:
   target: email@provider.com


EDIT: after posting the 3 spaces in front of target gone...
message: test
title: test
data:
___target: email@provider.com

**Comment by Je-sse** [comment]
> Hi Je-sse, i had succsess with:
> 
> message: test
> title: test
> data:
> target: [email@provider.com](mailto:email@provider.com)
> 
> EDIT: after posting the 3 spaces in front of target gone...
> message: test
> title: test
> data:
> ___target: [email@provider.com](mailto:email@provider.com)

Hi Competizione,

That did the trick, thank you so much!
